services:
  pictosearch:
    container_name: pictosearch
    tty: true
    stdin_open: true
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    restart: always