version: "3"

services:
  pictosearch:
    container_name: pictosearch
    tty: true
    stdin_open: true
    build:
      context: .
      # possible to use development here instead
      target: production
    ports:
      - "8070:8080"
    restart: always