version: "3"

services:
  pictosearch:
    container_name: pictosearch
    tty: true
    stdin_open: true
    build:
      context: .
      # possible to use development here instead
      target: development
    ports:
      # development port is usually 3000
      - "8070:3000"
    # for development, uncomment this to map most recent files to the container
    volumes:
      - .:/app
    restart: always